hikaricp-common/src/main/java/com/zaxxer/hikari/hibernate/HikariConnectionProvider.java

Issue 273 (https://github.com/brettwooldridge/HikariCP/issues/273), special case for when called to unwrap a DataSource, copying the same behavior as the ConnectionProvider implementations by Hibernate.

Unwrap ConnectionProvider to DataSource

---

README.md

[jTDS](http://jtds.sourceforge.net/) is LGPL-licensed driver for MS SQL.

Add open source jTDS MS SQL driver to DataSources

---

README.md

The jConnect Driver (as of version 7.0) has two package implementations for the Driver: 1) com.sybase.jdbcx.SybDataSource and 2) com.sybase.jdbc4.jdbc.SybDataSource .
If 1) is used then an exception is thrown from the HikariCP since it's looking for a default constructor that is not there and throws the following exception upon initialisation:
Caused by: java.lang.InstantiationException: com.sybase.jdbcx.SybDataSource
at java.lang.Class.newInstance(Class.java:418)
at com.zaxxer.hikari.util.UtilityElf.createInstance(UtilityElf.java:117)
... 62 more
Caused by: java.lang.NoSuchMethodException: com.sybase.jdbcx.SybDataSource.()
at java.lang.Class.getConstructor0(Class.java:3069)
at java.lang.Class.newInstance(Class.java:403)
... 63 more
Switching to 2) the driver starts up successfully and …

Changing the documented jConnect Sybase Driver to an implementation that works

---

README.md

Use headers instead of just bold titles makes it easier to link to specific parts of documentation.

Small format details

---

README.md

It took me quite some time to figure out how to configure a custom port.
Finally found at: https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/ds/PGSimpleDataSource.html
Note: You could probably add a link to any data-source Java-docs in the data-source-class-name-list and add a note that any property supported by data-source can be defined in as property (if not there already).

Add example how to configure port for PGSimpleDataSource

---

src/main/java/com/zaxxer/hikari/HikariConfig.java
src/main/java/com/zaxxer/hikari/HikariDataSource.java
src/main/java/com/zaxxer/hikari/metrics/CodahaleMetricsTrackerFactory.java
src/main/java/com/zaxxer/hikari/metrics/MetricsTrackerFactory.java
src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/test/java/com/zaxxer/hikari/TestMetrics.java

This pull request intends to allow the use of other metrics libraries than Dropwizard Metrics. It uses the current MetricsTracker class without modification, it simply adds a MetricsTrackerFactory interface that will create an instance of a subclass of MetricsTracker.
The Dropwizard/CodeHale current implementation has been adapted to use a MetricsTrackerFactory, some methods have been rewritten but no method has been deleted or deprecated.

Allow the use of a user provided MetricsTracker

---

README.md

Hilariously, I saw this typo in 'Dijkstra'.
I think I know how to write that name.

Typo in Dijkstra

---

hikaricp-common/src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java

If an exception occurs while closing a connection's open statements
(e.g. NullPointerException due to concurrent close of statement with
connection), the connection was not returned to the pool.
We now check for this possibility and ensure the connection is returned
to the pool.

[2.3.x] Ensure closed connections returned to pool

---

src/main/java/com/zaxxer/hikari/HikariConfig.java
src/main/java/com/zaxxer/hikari/HikariDataSource.java
src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/main/java/com/zaxxer/hikari/pool/PoolElf.java
src/test/java/com/zaxxer/hikari/ShutdownTest.java
src/test/java/com/zaxxer/hikari/TestValidation.java

HikariPool: Log consitency
PoolElf: I think two more round trips to db/driver is overkill (for pool
to support bad driver) especially jdbc spec reads 'closing statement
must close any current result set'. It is already slow (compare to
others) having network timeout as well as query timeout to validate
connection!

HikariPool: Log consitency

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/main/java/com/zaxxer/hikari/pool/PoolBase.java

no need for trip to driver/db for closing con.
http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#close() states
Calling the method close on a Connection object that is already closed is a no-op.
moreover isClosed() was not guarded by network timeout.

removed isClosed() check

---

src/main/java/com/zaxxer/hikari/pool/PoolBase.java

Some `DataSource` implementations (like [`BasicDataSource`](https://commons.apache.org/proper/commons-dbcp/api-1.4/org/apache/commons/dbcp/BasicDataSource.html) or [`DriverManagerDataSource`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/datasource/DriverManagerDataSource.html)) do not support setting a login timeout. `UnsupportedOperationException` is thrown in these cases.
When a delegate `dataSource` is set for the HikariCP, it tries to invoke this method on the delegate. Only log a warning in this case instead of failing to initialize the HikariCP.
This is amongst others relevant for using HikariCP in Grails, which creates instances of `org.springframework.jdbc.datasource.DriverManagerDataSource` (at least in version 2.2.4).

do not fail if setLoginTimeout on delegate data source is not supported

---

src/test/java/com/zaxxer/hikari/pool/TestMetrics.java

There I am again, I haven't had the spurious wake-up issue since, which is good.
I know that the reference code is not exactly public, but it makes the skip reason readable enough.
Let me know what you think.

Skip the `testMetricUsage` test on Windows

---

src/main/java/com/zaxxer/hikari/metrics/MetricsTracker.java
src/main/java/com/zaxxer/hikari/metrics/dropwizard/CodaHaleMetricsTracker.java
src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/main/java/com/zaxxer/hikari/pool/PoolBase.java

Added `MetricsTracker.recordConnectionTimeout()` and tied that into `HikariPool.getConnection()` when we hit the connection timeout threshold.  Also added an implementation to `CodaHaleMetricsTracker` with a counter and a meter.

Add metric for recording count and rate of connection timeouts

---

src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java

Not handling it avoids eviction of the connection and corrupts the pool.
For example the following NullPointerException is thrown when trying to use the pool afterwards:
java.lang.NullPointerException at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:128)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:171)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
.......

Add ORA-02399: exceeded maximum connect time to SQL_ERRORS.

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java

Motivation:
Shutdown may be invoked as a result of checkFailFast failing resulting in an NPE as the executors are setup later in the constructor.
Modifications:
Add null checks before trying to shutdown the executors.
Result:
"Graceful" shutdown.

Shutdown will throw NPE if invoked from checkFailFast

---

src/main/java/com/zaxxer/hikari/util/PropertyElf.java
src/main/java/com/zaxxer/hikari/util/UtilityElf.java

Motivation:
toUpperCase works according to Locale settings, for example if your computer locale is Turkish, "idleTimeout" property turns into "setİdleTime" beacuse upper "i" is "İ" in Turkish.
Modifications:
Invoke toUpperCase with Locale.ENGLISH.
Result:
Fixes #641.
PropertyBeanSetter should work with Turkish locale.

PropertyBeanSetter uses default locale

---

src/test/java/com/zaxxer/hikari/pool/TestConnectionTimeoutRetry.java

We are researchers working on identifying redundant tests in a test suite. Our analysis of finding redundant tests involve each test's dynamic code coverage and their potential fault-detection capability.
Through our analysis, we found that the tests com.zaxxer.hikari.pool.TestConnectionTimeoutRetry.testConnectionRetries, com.zaxxer.hikari.pool.TestConnectionTimeoutRetry.testConnectionRetries4 are redundant with respect to one another. In this pull request, we are proposing to keep only the test com.zaxxer.hikari.pool.TestConnectionTimeoutRetry.testConnectionRetries while adding @Ignore annotations to the remaining test. However, as we believe these tests are identical, any one of them can be kept while skipping the remaining test.
If you do not believe any of these tests should be …

Removing test redundant for com.zaxxer.hikari.pool.TestConnectionTimeoutRetry.testConnectionRetries

---

src/main/java/com/zaxxer/hikari/util/ClockSource.java
src/test/java/com/zaxxer/hikari/util/ClockSourceTest.java

Currently, it uses GREEK SMALL LETTER MU (U+03BC), which doesn't display in the command prompt on Windows. After this commit, it uses MICRO SIGN (U+00B5).

Change what character is used for microseconds

---

README.md

The leading slash (which causes the search to start at the root of the classpath) is essential in most cases-rarely would db config be bundled alongside the class of interest in the package structure--I think this clarification in the example will help novices to HikariCP (like me).

Helpful clarification on .properties location

---

src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java

Calling sqle.getNextException() will return the same exception as sqle is never reassigned in the loop.

Unwrap chained exceptions.

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/test/java/com/zaxxer/hikari/pool/HouseKeeperCleanupTest.java

Periodic house-keeping task is scheduled during construction of
HikariPool. The resulting scheduled task is not stored and therefore it
is not cancelled during pool shutdown.
With standard behaviour, when executor is managed by HikariPool itself,
it is not an issue, because the executor is shut down on pool shutdown.
But when a custom (long running) scheduled executor is supplied via
setScheduledExecutorService, tasks are kept indefinitely causing a
memory leak.

Cancel HouseKeeper task on pool shutdown

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/main/java/com/zaxxer/hikari/pool/PoolBase.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java
src/test/java/com/zaxxer/hikari/pool/MetricsTrackerTest.java

We noticed that the pool.Wait metric only captured the timings for successful connection requests and doesn't capture when a connection request times out.
I didn't want to mess with IMetricsTrackerDelegate.recordBorrowStats() so I created recordBorrowTimeoutStats() and implementation in MetricsTrackerDelegate instead.  Feel free to tweak to your liking.

pool.Wait metric doesn't include timed out requests

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java

In retrospect on #825, this is a better place to capture the metric.  In #825, it would only capture the timing if the connection bag returned null but it would not capture the timing if the bag returned an entry and the connection then failed validation or was evicted.  Moving the statement to outside of the do/while will capture both scenarios.

Better place to capture pool.Wait metric

---

src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactory.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollectorTest.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java

Hey.
This PR introduces a new constructor in `PrometheusMetricsTracker` and a constructor overload in `PrometheusMetricsTrackerFactory` to enable configuration of whatever Promethes `CollectorRegistry` one might want to use. It's completely backwards compatible and shouldn't affect any existing codebase relying on this.

Added support for non-default Prometheus CollectorRegistry

---

src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactory.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollectorTest.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java

I reverted commit #876 and rebased #851 with minor naming changes. In addition to these, I changed 'connection timeout counter' name's suffix from 'count' to 'total' which all prometheus counters use. That might be breaking change for people who use that metric.

Fix prometheus metrics to support multiple hikaricp pools

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/main/java/com/zaxxer/hikari/pool/ProxyLeakTask.java
src/main/java/com/zaxxer/hikari/pool/ProxyLeakTaskFactory.java

This change splits off a ProxyLeakTaskFactory from the ProxyLeakTask class
so that scheduling the task is done after its constructor completes. This
prevents publishing the tasks "this" reference during construction.
See ["Safe construction techniques" by Brian Goetz](https://www.ibm.com/developerworks/java/library/j-jtp0618/index.html).

Introduce factory for leak detection tasks

---

src/main/java/com/zaxxer/hikari/HikariConfig.java

I use HikariCP in my project and set JDBC URL with password property. I found the password in JDBC URL is not masked while directly set password is. I think it's good to mask it as well. Could you consider to merge this change?

Mask password in JDBC URL

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java

ClassNotFoundException is thrown during `DataSource#getConnection()` when `io.dropwizard.metrics:metrics-core`  is not available in the class path.

Fixed ClassNotFoundException when com.codahale.metrics.MetricRegistry is not in the classpath

---

src/main/java/com/zaxxer/hikari/pool/ProxyLeakTask.java

Thread names are often modified to include context information like session details in complex multithreaded systems.  Even when they haven't the thread name can give vital clues to link potential leaks to other information in a log file like request details or exceptions that may have occurred earlier.

Add the thread name to potential leak detection warnings.

---

src/test/java/com/zaxxer/hikari/util/TestFastList.java

`com.zaxxer.hikari.util.FastList::clear()` sets the `size` variable to `0` and also sets all the elements in the `FastList` to `null`. However, `com.zaxxer.hikari.util.TestFastList::testClear()` only checks that `size` is `0`. This PR changes `testClear()` to also check that all elements in the list are set to `null` after calling `clear()`.

test that FastList::clear() sets all elements to null

---

src/main/java/com/zaxxer/hikari/util/UtilityElf.java

Added a constant that represents the SQL server's snapshot isolation level and added a case with the constant.
Configuring the isolation level with Spring Boot 2's application.yml works.

Added a support for SQL server's specific isolation level (Snapshot)

---

src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java

The current configuration of [summary](https://prometheus.io/docs/concepts/metric_types/#summary) type prometheus metrics in `hikaricp` only provides two values:
- `count` of observations
- `sum` of observed values
for the following metrics:
- connection acquisition time
- connection usage time
- connection creation time
One can derive additional useful metrics based on just these two values:
- `avg` = `sum` / `count`
- `rate` = delta(`count`) / delta(`time`)
- sliding`avg` = delta(`sum`[5m]) / delta(`count`[5m])
Prometheus summaries also support calculation of quantiles that are more useful than averages during analyses. 
I propose to enable the following quantiles calculation in a 5 minute sliding window:
- `0.5` (median) with error of `0.05`
- `0.95` with error of `0.01`
- `0.99` with …

Enable quantiles calculation in prometheus metrics

---

README.md

`org.firebirdsql.pool.FBSimpleDataSource` was deprecated in Jaybird 2.2 and will be removed in Jaybird 4. Replacement class is `org.firebirdsql.ds.FBSimpleDataSource`.

Update Firebird datasource

---

src/main/java/com/zaxxer/hikari/HikariConfig.java
src/main/java/com/zaxxer/hikari/pool/HikariPool.java
src/main/java/com/zaxxer/hikari/util/UtilityElf.java
src/test/java/com/zaxxer/hikari/pool/TestMetrics.java

Allow anonymous subclasses of MetricRegistry.
Also changing check for metrics libraries from classname contains to assignableFrom the metrics class. In case of class passed in which is not assignable from MetricRegistry of MeterRegistry it should still throw the IllegalArgumentException not ClassCastException.
Both use cases are added in TestMetrics

Allowing anonymous subclasses of MetricRegistry.

---

src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTracker.java

Micrometer's gauges were breaking after the `PoolStats` object they weakly referenced was garbage collected. This change holds a strong reference to the `PoolStats` object in `MicrometerMetricsTracker` to avoid this issue.
See http://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing
I noticed that the HikariCP gauges were showing `NaN` for their value sometime after application startup. The recently added documentation in Micrometer linked above helped me track down the issue.

Maintain strong reference to PoolStats for Micrometer gauges

---

src/test/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTrackerTest.java

For example, I tried the wrong name as the following but the result was green.
The current test code doesn't seem to be able to test MicrometerMetricsTracker correctly.
```java
Assert.assertNotNull(mockMeterRegistry.find("xxx"));
```

`mockMeterRegistry#find(String)` doesn't seem to return null

---

src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTracker.java

See following comment from Micrometer maintainer https://github.com/micrometer-metrics/micrometer/issues/91#issuecomment-365780694. The hard-coded client-side percentile in HikariCP will make an extra time series whether the user wants it or not. Ultimately, to configure the percentiles or histogram they want, they will have to use a `MeterFilter`. I've added documentation for how they can do that.
If you don't want the public constant or documentation changes, feel free to take just the commit that removes hard-coded percentiles.
/cc @jkschneider @checketts

Remove hard-coded percentiles for Micrometer metrics

---

src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactory.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollectorTest.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactoryTest.java
src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java

Added a constructor to `PrometheusMetricsTrackerFactory` that allows to pass in a `CollectorRegistry` instance.
Removed the `static` modifier from the collector field since with the new constructor you may theoretically have more than one instance of the factory using a different `CollectorRegistry` instance each.
fixes #1181

allow to pass in a prometheus CollectorRegistry (fixes #1181)

---

src/main/java/com/zaxxer/hikari/pool/HikariPool.java

Use `orElseGet` to delay creation of DefaultThreadFactory until falling through to the or else part of the optional.

Use orElseGet to delay call until necessary

---

README.md
documents/Welcome-To-The-Jungle.md
src/test/java/com/zaxxer/hikari/mocks/MockDataSource.java

This pull request fixes the typos in this repository. Although I am not a native English speaker, [misspell](https://github.com/client9/misspell) detected obvious mistakes for us. I've fixed them except for false positives.

Fix typos detected by github.com/client9/misspell
