brettwooldridge/HikariCP

- .gitignore
Hello!
Ignore the IntelliJ generated 'out' directory.
-=david=-
> Ignore IntelliJ 'out' directory.

- src/main/java/com/zaxxer/hikari/HikariConfig.java
- src/main/java/com/zaxxer/hikari/HikariDataSource.java
- src/main/java/com/zaxxer/hikari/HikariJNDIFactory.java
- src/main/java/com/zaxxer/hikari/metrics/CodaHaleMetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/MetricsTracker.java
- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/main/java/com/zaxxer/hikari/pool/LeakTask.java
- src/main/java/com/zaxxer/hikari/pool/PoolBagEntry.java
- src/main/java/com/zaxxer/hikari/pool/PoolUtilities.java
- src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java
- src/main/java/com/zaxxer/hikari/proxy/JavassistProxyFactory.java
- src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java
- src/main/java/com/zaxxer/hikari/util/DefaultThreadFactory.java
- src/main/java/com/zaxxer/hikari/util/DriverDataSource.java
- src/main/java/com/zaxxer/hikari/util/UtilityElf.java
- src/test/java/com/zaxxer/hikari/PostgresTest.java
- src/test/java/com/zaxxer/hikari/ShutdownTest.java
- src/test/java/com/zaxxer/hikari/TestConnectionCloseBlocking.java
- src/test/java/com/zaxxer/hikari/TestConnectionTimeoutRetry.java
- src/test/java/com/zaxxer/hikari/TestConnections.java
Some improvements. Nothing particularly big, but still useful (I hope). WDYT?
> Improvements

- README.md
- src/main/java/com/zaxxer/hikari/HikariConfig.java
Fixed Readme too...added missing changes from master
> Fix Issue 375 ..restore thing that was not broken

- CHANGES
- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/main/java/com/zaxxer/hikari/pool/PoolBagEntry.java
- src/main/java/com/zaxxer/hikari/pool/PoolElf.java
tweak isConnectionAlive(): do not set query timeout if network time out is already set
shutdown(): mainly, close connection bag after closing executor first.
> tweak isConnectionAlive and few other

- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
some details from
https://github.com/brettwooldridge/HikariCP/issues/379
based on original pull request
https://github.com/brettwooldridge/HikariCP/pull/383
> revise connection pool cleanup logic by reducing unncessary loop,

- src/main/java/com/zaxxer/hikari/HikariConfig.java
ClassLoader.getResourceAsStream() and Class.getResourceAsStream() are
different. Refer to http://stackoverflow.com/a/1464366/524588
> fixed comment

- src/main/java/com/zaxxer/hikari/pool/PoolElf.java
- src/test/java/com/zaxxer/hikari/mocks/StubConnection.java
auto commit and read only should be treated similarly too. do not set explicitly, let it be driver default.
> do not set connection with property that user have not specified.

- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/main/java/com/zaxxer/hikari/pool/Mediator.java
- src/main/java/com/zaxxer/hikari/pool/PoolEntry.java
- src/main/java/com/zaxxer/hikari/proxy/ConnectionProxy.java
- src/main/java/com/zaxxer/hikari/proxy/ConnectionState.java
ConnectionProxy: made memebers private, added missing methods of
connectionState. not sure why ide does not complain !
> Mediator: simplified check of validation modes

- README.md
- src/main/java/com/zaxxer/hikari/metrics/CodaHaleMetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/MetricsTracker.java
- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/main/java/com/zaxxer/hikari/pool/PoolBase.java
- src/main/java/com/zaxxer/hikari/pool/PoolEntry.java
- src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java
- src/main/java/com/zaxxer/hikari/pool/ProxyLeakTask.java
- src/main/java/com/zaxxer/hikari/pool/ProxyResultSet.java
- src/main/java/com/zaxxer/hikari/pool/ProxyStatement.java
- src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java
- src/test/java/com/zaxxer/hikari/ShutdownTest.java
> removed redundant creationTime. lastAceess is initialized at creation as

- src/main/java/com/zaxxer/hikari/metrics/MetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/dropwizard/CodaHaleMetricsTracker.java
- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/main/java/com/zaxxer/hikari/pool/PoolBase.java
- src/main/java/com/zaxxer/hikari/pool/PoolEntry.java
'readonly' before commit/rollback.
> renamed method/var names, moved toString() to PoolBase, checking for

- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/main/java/com/zaxxer/hikari/util/ConcurrentBag.java
replaced old code now that you are done with fix
> removed check (claimed != null) from hotpath

- README.md
Kind of redundant considering the maven info below, but at least it always displays the latest version available.
> Added maven-central badge to README.md

- README.md
Added OrientDataSource to the list of popular datasources. I have tested OrientDB with HikariCP and it is perfectly working!
> Updated Popular DataSource list

- src/main/java/com/zaxxer/hikari/pool/PoolBase.java
side effect of allowing validationTimeout as low as 250ms
> bugfix: 0 is infinite for isValid(). made minimum 1sec

- pom.xml
- src/main/java/com/zaxxer/hikari/HikariConfig.java
- src/main/java/com/zaxxer/hikari/HikariDataSource.java
- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java
- src/main/java/com/zaxxer/hikari/pool/ProxyResultSet.java
- src/main/java/com/zaxxer/hikari/pool/ProxyStatement.java
- src/main/java/com/zaxxer/hikari/util/ClockSource.java
- src/main/java/com/zaxxer/hikari/util/JavassistProxyFactory.java
- src/main/java/com/zaxxer/hikari/util/Sequence.java
- src/test/java/com/zaxxer/hikari/pool/ConnectionRaceConditionTest.java
- src/test/java/com/zaxxer/hikari/pool/MiscTest.java
- src/test/java/com/zaxxer/hikari/pool/PostgresTest.java
- src/test/java/com/zaxxer/hikari/pool/ShutdownTest.java
- src/test/java/com/zaxxer/hikari/pool/TestConcurrentBag.java
- src/test/java/com/zaxxer/hikari/pool/TestFastList.java
- src/test/java/com/zaxxer/hikari/pool/TestProxies.java
- src/test/java/com/zaxxer/hikari/pool/UnwrapTest.java
- Minor IntelliJ suggestions applied.
- Maven dependencies and plugins updated to latest.
> IntelliJ inspections fixes and Maven updates

- src/test/java/com/zaxxer/hikari/pool/ConcurrentCloseConnectionTest.java
> Add test to demonstrate concurrency problem

- pom.xml
- src/main/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollector.java
- src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactory.java
- src/test/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollectorTest.java
- src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java
I want to export metrics data to prometheus' simpleclient.
I sent p-r for Prometheus repo. Then, @brian-brazil recommend me to p-r for hikaricp's repo.
https://github.com/prometheus/client_java/pull/118
Ref #321
> Add prometheus support

- pom.xml
- src/main/java/com/zaxxer/hikari/util/FastList.java
Closes https://github.com/brettwooldridge/HikariCP/issues/672 .
> Implement List directly instead of extending ArrayList.

- src/main/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollector.java
- src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactory.java
- src/main/java/com/zaxxer/hikari/pool/PoolBase.java
- src/test/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollectorTest.java
- src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java
- src/test/java/com/zaxxer/hikari/mocks/StubBaseConnection.java
- src/test/java/com/zaxxer/hikari/pool/ConcurrentCloseConnectionTest.java
- src/test/java/com/zaxxer/hikari/pool/ConnectionRaceConditionTest.java
- src/test/java/com/zaxxer/hikari/pool/ConnectionStateTest.java
- src/test/java/com/zaxxer/hikari/pool/ExceptionTest.java
- src/test/java/com/zaxxer/hikari/pool/IsolationTest.java
- src/test/java/com/zaxxer/hikari/pool/RampUpDown.java
- src/test/java/com/zaxxer/hikari/pool/StatementTest.java
- src/test/java/com/zaxxer/hikari/pool/TestConnectionCloseBlocking.java
- src/test/java/com/zaxxer/hikari/pool/TestConnectionTimeoutRetry.java
- src/test/java/com/zaxxer/hikari/pool/TestFastList.java
- src/test/java/com/zaxxer/hikari/pool/TestHibernate.java
- src/test/java/com/zaxxer/hikari/pool/TestPropertySetter.java
- src/test/java/com/zaxxer/hikari/pool/TestProxies.java
Fix for https://github.com/brettwooldridge/HikariCP/issues/665
> Add license headers

- src/main/java/com/zaxxer/hikari/metrics/dropwizard/CodaHaleMetricsTracker.java
- src/test/java/com/zaxxer/hikari/metrics/dropwizard/CodaHaleMetricsTrackerTest.java
> Remove ConnectionTimeoutRate on close

- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/test/java/com/zaxxer/hikari/pool/ConnectionPoolSizeVsThreadsTest.java
> Burst fix attempt2

- src/main/java/com/zaxxer/hikari/HikariConfig.java
- src/main/java/com/zaxxer/hikari/util/DriverDataSource.java
> Fixes #878 Searching for driverClass in both hikari class classloader and Thread Context ClassLoader

- src/main/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollector.java
- src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerFactory.java
- src/test/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTrackerTest.java
Hello, 
In PR #890, I intended to support multiple data source for prometheus metrics. But, it turns out it has missing parts and its tests are misleading shown in #927 . In this PR, I aimed to fix its missing parts and test. I would be grateful, if you can check it anytime you are available @mmimica, @brettwooldridge. 
Thanks in advance,
> Fix Prometheus metric collector for multiple data config

- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
Closes https://github.com/brettwooldridge/HikariCP/pull/842
> Log better message when connection was evicted or dead.

- src/main/java/com/zaxxer/hikari/HikariConfig.java
Creating a new PR from scratch because I messed up the rebase of PR #697.
> Fallback to four digit random pool name and log INFO when in security sandbox

- src/main/java/com/zaxxer/hikari/HikariConfig.java
- src/main/java/com/zaxxer/hikari/HikariDataSource.java
- src/test/java/com/zaxxer/hikari/pool/HouseKeeperCleanupTest.java
Fixes #892 and should prevent further confusion.
> Split copyState to copyStateTo and copyStateFrom

- pom.xml
- src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTracker.java
@brettwooldridge The RC updated the api fair amount. 
@jkschneider Mind double checking this?
> Update to match Micrometer updated RC api

- pom.xml
- src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTracker.java
I apologize @brettwooldridge I just found out the latest rc removed one more method. It has stabilized now so we don't expect any further breakages. Right @jkschneider?
> Update for Micrometer.rc3

- src/main/java/com/zaxxer/hikari/metrics/PoolStats.java
- src/main/java/com/zaxxer/hikari/metrics/dropwizard/CodaHaleMetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTracker.java
- src/main/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollector.java
- src/main/java/com/zaxxer/hikari/pool/HikariPool.java
- src/test/java/com/zaxxer/hikari/metrics/dropwizard/CodaHaleMetricsTrackerTest.java
- src/test/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTrackerTest.java
- src/test/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollectorTest.java
Add metrics to alert when remaining pooled connections are insufficient in quantity.
> Add pool metrics

- src/test/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTrackerTest.java
add test case for new metrics.
ref: #1110
> add test case for new metrics

- src/main/java/com/zaxxer/hikari/HikariConfig.java
no operational or logical change, only this refactor. i think, reusing the method "checkIfSealed" is a better style.
> refactor: extract seal check into method and reuse

- src/main/java/com/zaxxer/hikari/util/DriverDataSource.java
> log loaded driver when using jdbcUrl (Closes #1018)

- README.md
> [DOCS] Fix dead link to Wix engineering blog post

- src/main/java/com/zaxxer/hikari/HikariDataSource.java
- src/test/java/com/zaxxer/hikari/pool/TestIsRunning.java
> Fix for #1226 and unit tests.
